name: CD

on:
  push:
    branches:
      - production

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production server.
      uses: appleboy/ssh-action@master
      with:
          command_timeout: "10m"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/Spool
            git checkout production
            git pull
            cd ..
            sudo docker-compose down
            sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build &

